app/models.py
from datetime import datetime

from sqlalchemy import func

from app import db


class ApiMixin:

    @classmethod
    def column_names(cls):
        """ Returns list of column names

        Returns:
            list
        """
        return cls.__table__.columns.keys()

    @classmethod
    def column_properties(cls):
        """Returns list of table columns dicts

        Returns:
            list(dict): list of dicts describing the table columns
        """
        columns = []
        for column in cls.__table__.columns:
            columns.append({
                "name" : column.name,
                "type" : str(column.type),
                "nullable" : column.nullable,
                "primary_key" : column.primary_key,
                "unique" : column.unique,
                "default" : column.default,
            })
        return columns

    def update(self, **kwargs):
        """ Updates self by given data, dict of column names and values
        Sanity check not included, invalid value types will pop up during commit

        Args:
            kwargs: column names and values

        Returns:
            self

        Raises:
            KeyError: if any key isn't a valid column name
        """
        # check if all keys are valid column names
        if not all(key in self.column_names() for key in kwargs.keys()):
            raise KeyError

        for key, value in kwargs.items():
            setattr(self, key, value)

        return self


class SensorReading(db.Model, ApiMixin):
    __tablename__ = "sensor_reading"

    id = db.Column(db.Integer, primary_key=True)
    sensor_id = db.Column(db.Integer, 
        db.ForeignKey("sensor.id", onupdate="CASCADE", ondelete="CASCADE"),
        nullable=False)
    value = db.Column(db.Float, nullable=True)
    datetime = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    # relationships
    sensor = db.relationship("Sensor", back_populates="readings")

    def __repr__(self):
        return "SensorReading<id={}, sensor_id={}, value={}, datetime={}>".format(
            self.id, self.sensor_id, self.value, self.datetime
        )

    def to_dict(self, *args):
        """Writes object to dictionary

        Args:
            *args: Strings of columns that should be used. if empty, every column is included
        """
        data = {
            "id" : self.id,
            "sensor_id" : self.sensor_id,
            "value" : self.value,
            "datetime" : self.datetime.strftime('%Y-%m-%dT%H:%M:%SZ'),
        }
        # reduce dict by *args values
        if len(args) > 0:
            data = {arg : data[arg] for arg in args}
        return data

    @classmethod
    def timeinterval_grouper(cls, timeinterval):
        """ Returns func that returns clustered timestamp values

        Args:
            interval (int-str): cluster datetime by x seconds or strfformatter string
                check mapper values
                
        Returns:
            return func object (use for queries)
        """
        
        if isinstance(timeinterval, str):
            mapper = {"Y": 1, "m": 2, "d": 3, "H": 4, "M": 5, "S": 6}
            i = mapper.get(timeinterval)
            if i is None:
                raise ValueError("timeinterval must be an int or one of the following chars: {}".format(list(mapper.keys())))
            formatter = ["%Y-", "%m-", "%dT", "%H:", "%M:", "%S"]
            filler = ["0-", "01-", "01T", "00:", "00:", "00"]
            format_str = "".join(formatter[:i] + filler[i:])
            return func.strftime(format_str, cls.datetime)
        # seconds
        return func.strftime("%s", cls.datetime) / timeinterval * timeinterval



class Sensor(db.Model, ApiMixin):
    __tablename__ = "sensor"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    unit = db.Column(db.String)
    description = db.Column(db.String)

    # relationships
    readings = db.relationship(
        "SensorReading",
        back_populates="sensor",
        cascade="all, delete-orphan",
        passive_deletes=True, # let cascading deletes be managed by db
    )

    def __repr__(self):
        return "Sensor<id={}, name={}, unit={}, description={}>".format(
            self.id, self.name, self.unit, self.description
        )

    def to_dict(self):
        return {
            "id" : self.id,
            "name" : self.name,
            "unit" : self.unit,
            "description" : self.description,
        }

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField
from wtforms.validators import DataRequired


class SensorForm(FlaskForm):
    id = IntegerField("Id")
    name = StringField("Name", [DataRequired()])
    unit = StringField("Unit")
    description = StringField("Description")

app/__init__.py
from config import Config
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
migrate = Migrate()


def create_app(config=Config):
    """app factory

    Args:
        config: Config object for app.config

    Returns:
        Flask app
    """
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)

    # blueprint registering
    from app.main import bp as bp_main
    app.register_blueprint(bp_main)

    from app.errors import bp as bp_errors
    app.register_blueprint(bp_errors)

    from app.api import bp as bp_api
    app.register_blueprint(bp_api, url_prefix='/api')

    return app

if Config.SQLALCHEMY_DATABASE_URI.startswith("sqlite"):
    from sqlalchemy import event
    from sqlalchemy.engine import Engine

    @event.listens_for(Engine, "connect")
    def set_sqlite_pragma(dbapi_connection, connection_record):
        cursor = dbapi_connection.cursor()
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.close()

app/api/__init__.py
from flask import Blueprint

bp = Blueprint("api", __name__)

from app.api import sensors

app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from app.main import routes

app/main/routes.py
from app import models
from app.main import bp
from app.main.forms import SensorForm
from flask import abort, render_template


@bp.route("/")
def index():
    return render_template("main/index.html")


@bp.route("/sensor")
def sensor():
    return render_template("main/sensor.html", title="Sensor")


@bp.route("/sensor/<int:id>")
def sensor_id(id):
    s = models.Sensor.query.get(id)
    if s is None:
        return abort(404)
    
    form = SensorForm()
    # prefill sensor form
    for key in models.Sensor.column_names():
        setattr(getattr(form, key), "data", getattr(s, key))

    return render_template("main/sensor_id.html", title="Edit Sensor", form=form)

@bp.route("/sensor/new")
def sensor_new():
    form = SensorForm()
    return render_template("main/sensor_new.html", title="New Sensor", form=form)

@bp.route("/about")
def about():
    return render_template("main/about.html", title="About")

app/templates/base.html
<!DOCTYPE html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Bottled Home{% if title %} - {{ title }}{% endif %}</title>
    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('main.sensor') }}">Sensor</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('main.about') }}">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages %}
        {% if category == 'message' %}
        {% set category = 'primary' %}
        {% endif %}
        <div class="alert alert-{{ category }}" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    {% block script %}{% endblock %}
    {% endblock %}
</body>

app/templates/led.html
{% extends "base.html" %}

{% block content %}
{{ super() }}
<h1>LED</h1>
<input type="color" id="color" class="form-control form-control-color">
<div id=modesRadio></div>
{% endblock %}


{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='led.js') }}"></script>
{% endblock %}

app/templates/main/_sensor.html
<div class="form-group">
    {{ form.id.label }}
    {{ form.id(class="form-control", placeholder="Enter id") }}
</div>
<div class="form-group">
    {{ form.name.label }}
    {{ form.name(class="form-control", placeholder="Enter name") }}
</div>
<div class="form-group">
    {{ form.unit.label }}
    {{ form.unit(class="form-control", placeholder="Enter unit") }}
</div>
<div class="form-group">
    {{ form.description.label }}
    {{ form.description(class="form-control", placeholder="Enter description") }}
</div>

app/templates/main/about.html
{% extends "base.html" %}
{% block content %}
{{ super() }}
<h1>About</h1>
<a href="https://github.com/lafila93/bottled_home">Github - bottled_home</a>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{% block content %}
{{ super() }}
<h1>Index</h1>
<p>Your advertisement could be here!</p>
{% endblock %}

app/templates/main/sensor.html
{% extends "base.html" %}


{% block head %}
{{ super() }}
<script src="https://cdn.plot.ly/plotly-2.3.1.min.js"></script>
{% endblock %}


{% block content %}
{{ super() }}
<h1>Sensor</h1>
<div id="plot"></div>
<div id="timedelta_buttons"></div>
<table>
    <tr>
        <th>Plot layout</th>
        <th>Group datetime by</th>
    </tr>
    <tr>
        <td><div id="plot_layout_radio" class="form-check"></div></td>
        <td><div id="timeinterval_radio" class="form-check"></div></td>
    </tr>
</table>
<div id="sensor_table"></div>
<a href="{{ url_for('main.sensor_new') }}">New Sensor</a>
{% endblock %}


{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='sensor.js') }}"></script>
<script>

$.ajax({
    url: "/api/sensor",
    success: function(sensors) {

        $("#sensor_table").html(buildSensorTable(sensors));

        getReadings(sensors, 60*60*24, function(readings) {
            plot("plot", sensors, readings)
        }, timeinterval=parsePlotConfigs().timeinterval)

        $("#timedelta_buttons").append(buildTimedeltaButtons("plot", sensors));

        var timer = updatePlot("plot", sensors);
    },
});

// create layout radio
for (const layout in Layout) {
    $("#plot_layout_radio").append(
        $("<div>").addClass("form-check").append(
            $("<input>").addClass("form-check-input plot-config").prop({
                type: "radio", name: "plot_layout", value: layout
            }),
            $("<label>").addClass("form-check-label").prop("for", layout)
                .html(layout)
        )
    )
}

// create timeinterval  radio
timeintervalMapper = {
    "Nothing": null,
    "5 Minutes": 60*5,
    "Hours": "H",
    "Days": "d",
    "Weeks": 60*60*24*7,
    "Months": "m",
    "Years": "Y",
}
for (const [grouper_label, value] of Object.entries(timeintervalMapper)) {
    $("#timeinterval_radio").append(
        $("<div>").addClass("form-check").append(
            $("<input>").addClass("form-check-input plot-config").prop({
                type: "radio", name: "plot_timeinterval", value: value
            }),
            $("<label>").addClass("form-check-label").prop("for", grouper_label)
                .html(grouper_label)
        )
    )
}

// set default radio from cookie
let cookie = getPlotCookie()
$("#plot_layout_radio :input[value='" + cookie.layout + "']").prop("checked", true);
$("#timeinterval_radio :input[value='" + cookie.timeinterval + "']").prop("checked", true)


// plot layout radio: click replot
$(".plot-config").on("click", function(event) {
    let config = parsePlotConfigs();
    setPlotCookieKey("layout", config.layout);
    setPlotCookieKey("timeinterval", config.timeinterval);
});

</script>
{% endblock %}

app/templates/main/sensor_id.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<script src="https://cdn.plot.ly/plotly-2.3.1.min.js"></script>
{% endblock %}

{% block content %}
{{ super() }}
<h1>Edit Sensor</h1>
<div id="inputs">
    {# _sensor.html contains the form for name, unit and description inputs #}
    {% include "main/_sensor.html" %}
    <button id="changeButton" class="btn btn-warning">Change</button>
    <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">DELETE</button>
</div>
<div id="output"></div>

<div id="plot"></div>
<div id="timedelta_buttons"></div>

<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Sensor and its readings?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>
                    Do you really want to delete this sensor and all of its readings?<br>
                    This cannot be undone.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="deleteConfirmationButton" type="button" class="btn btn-danger" data-bs-dismiss="modal">DELETE</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='sensor.js') }}"></script>
<script>
// get id by pathname
let id = window.location.pathname.split("/").slice(-1)[0];

$.ajax({
    url: "/api/sensor",
    data: {id: [id]},
    success: function(sensor) {
        // plot
        getReadings(sensor, 60*60*24, function(readings) {
            plot("plot", sensor, readings);
        });
        $("#timedelta_buttons").append(buildTimedeltaButtons("plot", sensor));
        var timer = updatePlot("plot", sensor);
    }
});

// change button
$("#changeButton").on("click", function() {
    // gather all the data in the textboxes
    let data = {}
    $("#inputs :input[type=text]").each(function(i) {
        data[this.name] = this.value === "" ? null : this.value;
    });

    $.ajax({
        url: "/api/sensor/" + id,
        method: "PUT",
        contentType: "application/json",
        data: JSON.stringify(data),
        success: function(result) {
            $("#output").html(JSON.stringify(result));
        },
        error: function(result) {
            $("#output").html(JSON.stringify(result));
        },
    });
});

// delete button
$("#deleteConfirmationButton").on("click", function() {
    $.ajax({
        url: "/api/sensor/" + id,
        method: "DELETE",
        success: function(result) {
            // redirect sensor
            window.location.href = "/sensor";
        },
        error: function(result) {
            $("#output").html(JSON.stringify(result));
        }
    });
});

</script>
{% endblock %}

app/templates/main/sensor_new.html
{% extends "base.html" %}

{% block content %}
{{ super() }}
<h1>New Sensor</h1>
<div id="inputs">
    {% include "main/_sensor.html" %}
    <input id="create" type="button" class="btn btn-primary" value="Create">
</div>
<div id="output"></div>
{% endblock %}

{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='sensor.js') }}"></script>
<script>

// create button
$("#create").on("click", function() {
    // gather all the data in the textboxes
    let data = {}
    $("#inputs :input[type=text]").each(function(i) {
        // fix empty strings (set null) and store in data object
        data[this.name] = this.value === "" ? null : this.value;
    });

    $.ajax({
        url: "/api/sensor",
        method: "POST",
        contentType: "application/json",
        data: JSON.stringify(data),
        success: function(result) {
            // redirect to new sensor site
            window.location.href = "/sensor/" + result["id"];
        },
        error: function(result) {
            $("#output").html(JSON.stringify(result));
        },
    });
});

</script>
{% endblock %}

app/templates/sensor_id.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<script src="https://cdn.plot.ly/plotly-2.3.1.min.js"></script>
{% endblock %}

{% block content %}
{{ super() }}
<h1>Edit Sensor</h1>
<div id="inputs">
    {% include "_sensor.html" %}
    <input id="change" type="button" class="btn btn-warning" value="Change">
    <input id="delete" type="button" class="btn btn-danger" value="DELETE">
</div>
<div id="output"></div>

<div id="plot"></div>
<div id="timedelta_buttons"></div>
{% endblock %}


{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='sensor.js') }}"></script>
<script>
// get id by pathname
let id = window.location.pathname.split("/").slice(-1)[0];

$.ajax({
    url: "/api/sensor",
    data: {id: [id]},
    headers: {
        Authorization: "Bearer " + Cookies.get("api_token"),
    },
    success: function(sensor) {
        // plot
        getReadingsPlot("plot", sensor, {days: 1});
        $("#timedelta_buttons").append(buildTimedeltaButtons("plot", sensor));
        var timer = updatePlot("plot", sensor);
    }
});

// change button
$("#change").on("click", function() {
    // gather all the data in the textboxes
    let data = {}
    $("#inputs :input[type=text]").each(function(i) {
        data[this.name] = this.value === "" ? null : this.value;
    });

    $.ajax({
        url: "/api/sensor/" + id,
        headers: {
            Authorization: "Bearer " + Cookies.get("api_token"),
        },
        method: "PUT",
        contentType: "application/json",
        data: JSON.stringify(data),
        success: function(result) {
            $("#output").html(JSON.stringify(result));
        },
        error: function(result) {
            $("#output").html(JSON.stringify(result));
        },
    });
});

// delete button
$("#delete").on("click", function() {
    $.ajax({
        url: "/api/sensor/" + id,
        headers: {
            Authorization: "Bearer " + Cookies.get("api_token"),
        },
        method: "DELETE",
        success: function(result) {
            // redirect sensor
            window.location.href = "/sensor";
        },
        error: function(result) {
            $("#output").html(JSON.stringify(result));
        }
    });
});

</script>
{% endblock %}

app/templates/sensor_new.html
{% extends "base.html" %}

{% block content %}
{{ super() }}
<h1>New Sensor</h1>
<div id="inputs">
    {% include "_sensor.html" %}
    <input id="create" type="button" class="btn btn-primary" value="Create">
</div>
<div id="output"></div>
{% endblock %}

{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='sensor.js') }}"></script>
<script>

// create button
$("#create").on("click", function() {
    // gather all the data in the textboxes
    let data = {}
    $("#inputs :input[type=text]").each(function(i) {
        // fix empty strings (set null) and store in data object
        data[this.name] = this.value === "" ? null : this.value;
    });

    $.ajax({
        url: "/api/sensor",
        headers: {
            Authorization: "Bearer " + Cookies.get("api_token"),
        },
        method: "POST",
        contentType: "application/json",
        data: JSON.stringify(data),
        success: function(result) {
            // redirect to new sensor site
            window.location.href = "/sensor/" + result["id"];
        },
        error: function(result) {
            $("#output").html(JSON.stringify(result));
        },
    });
});

</script>
{% endblock %}